### PR TITLE
fix: ensure that FilesManager.deleteFilesAsStatedInConfig deletes

### LINKED ISSUE #476: [backend] FileManager doesn't delete the directory in `FilesManager.deleteFilesAsStatedInConfig`
Even if configuration asks to do it. It is flagged by the compiler waring:
```compiler
[warn] -- [E175] Potential Issue Warning: /Users/jcentkowski/workspace/sml/adopt-tapir/backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala:39:8 
[warn] 39 |        for
[warn]    |        ^
[warn]    |        discarded non-Unit value of type cats.effect.IO[Unit]
[warn] 40 |          dir <- destinationDir
[warn] 41 |          _ <- dir.delete().pure[IO]
[warn] 42 |        yield ()
[warn] -- [E175] Potential Issue Warning: /Users/jcentkowski/workspace/sml/adopt-tapir/backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala:43:11 
[warn] 43 |      else ().pure[IO]
[warn]    |           ^^^^^^^^^^^
[warn]    |           discarded non-Unit value of type cats.effect.IO[Unit]
```

### PR DESCRIPTION
**Pull request by geminicaprograms**
When it is configured to do so. The IO(delete) operation was wrapped into another IO (blocking in this case) operation therefore only the outer was performed during the execution time. The problem was also indicated during compilation:

```
[warn] -- [E175] Potential Issue Warning: /Users/jcentkowski/workspace/sml/adopt-tapir/backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala:39:8
[warn] 39 |        for
[warn]    |        ^
[warn]    |        discarded non-Unit value of type cats.effect.IO[Unit]
[warn] 40 |          dir <- destinationDir
[warn] 41 |          _ <- dir.delete().pure[IO]
[warn] 42 |        yield ()
[warn] -- [E175] Potential Issue Warning: /Users/jcentkowski/workspace/sml/adopt-tapir/backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala:43:11
[warn] 43 |      else ().pure[IO]
[warn]    |           ^^^^^^^^^^^
[warn]    |           discarded non-Unit value of type cats.effect.IO[Unit]
```

The code was simplified, warning cleared and log statement was added to indicate if the deletion was successful.

Closes #476

### CODE REVIEW

File: backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala [hunk 1]
```diff
@@ -33,12 +34,11 @@ class FilesManager(config: StorageConfig):
...
-      else ().pure[IO]
-    }
+  def deleteFilesAsStatedInConfig(destinationDir: IO[File])(using cid: CorrelationId): IO[Unit] =
+    if config.deleteTempFolder then
+      for
+        dir <- destinationDir
+        deleted <- IO.blocking(dir.delete())
+        _ <- logger.info(s"The $dir deletion ${if (deleted) "succeeded" else "failed"}")
+      yield ()
+    else IO.unit
```
Comment (kciesielski) [inline backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala:44]: **nitpick:** You can use `whenA` instead of `if`.

```scala
(
for
  dir <- destinationDir
  deleted <- IO.blocking(dir.delete())
  _ <- logger.info(s"The $dir deletion ${if (deleted) "succeeded" else "failed"}")
yield ()
).whenA(config.deleteTempFolder)
```

**Review by adamw — APPROVED** [review]

File: backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala (hunk 1 above)
Comment (geminicaprograms) [reply backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala:44]: Done. Thanks for the hint 💪
