### PR TITLE
replaced blaze with ember

### LINKED ISSUE #302: Errors and periodical restarts
App dies every ~5 minutes.
Two types of exceptions can be observed. They happen when app is shutting down and someone calls the API from the outside:
```
{
  "@timestamp": "2023-01-18T09:06:26.815Z",
  "@version": "1",
  "level": "ERROR",
  "level_value": 40000,
  "logger_name": "org.http4s.blaze.server.Http1ServerStage$$anon$3",
  "message": "Error writing body",
  "stack_trace": "java.util.concurrent.RejectedExecutionException: This SelectorLoop is closed.
  at org.http4s.blaze.channel.nio1.SelectorLoop.enqueueTask(SelectorLoop.scala:110)
  at org.http4s.blaze.channel.nio1.SelectorLoop.executeTask(SelectorLoop.scala:85)
  at org.http4s.blaze.channel.nio1.NIO1HeadStage.writeRequest(NIO1HeadStage.scala:286)
  at org.http4s.blaze.channel.nio1.NIO1HeadStage.writeRequest(NIO1HeadStage.scala:243)
  at org.http4s.blaze.channel.nio1.NIO1HeadStage.writeRequest(NIO1HeadStage.scala:242)
  at org.http4s.blaze.pipeline.Tail.channelWrite(Stages.scala:111)
  at org.http4s.blaze.pipeline.Tail.channelWrite$(Stages.scala:90)
  at org.http4s.blazecore.IdleTimeoutStage.channelWrite(IdleTimeoutStage.scala:37)
  at org.http4s.blazecore.IdleTimeoutStage.writeRequest(IdleTimeoutStage.scala:52)
  at org.http4s.blaze.pipeline.Tail.channelWrite(Stages.scala:111)
  at org.http4s.blaze.pipeline.Tail.channelWrite$(Stages.scala:90)
  at org.http4s.blaze.server.Http1ServerStage.channelWrite(Http1ServerStage.scala:93)
  at org.http4s.blazecore.util.CachingChunkWriter.doWriteEnd(CachingChunkWriter.scala:104)
  at org.http4s.blazecore.util.CachingChunkWriter.writeEnd(CachingChunkWriter.scala:83)
  at org.http4s.blazecore.util.EntityBodyWriter.$anonfun$1(EntityBodyWriter.scala:60)
  at delay @ org.http4s.blazecore.util.EntityBodyWriter.writeEntityBody(EntityBodyWriter.scala:60)
  at flatMap @ org.http4s.blazecore.util.package$.fromFutureNoShift(package.scala:51)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at modify @ fs2.internal.Scope.close(Scope.scala:262)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at rethrow$extension @ fs2.Compiler$Target.compile$$anonfun$1(Compiler.scala:157)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Pull$.goCloseScope$1$$anonfun$1$$anonfun$3(Pull.scala:1215)
  at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:227)\n",
  "thread_name": "io-compute-3"
}
```

```
{
  "@timestamp": "2023-01-18T08:54:16.813Z",
  "@version": "1",
  "level": "ERROR",
  "level_value": 40000,
  "logger_name": "org.http4s.blaze.channel.nio1.NIO1HeadStage",
  "message": "Event loop closed. Closing in current thread.",
  "stack_trace": "java.util.concurrent.RejectedExecutionException: This SelectorLoop is closed.
  at org.http4s.blaze.channel.nio1.SelectorLoop.enqueueTask(SelectorLoop.scala:110)
  at org.http4s.blaze.channel.nio1.SelectorLoop.executeTask(SelectorLoop.scala:85)
  at org.http4s.blaze.channel.nio1.NIO1HeadStage.doClosePipeline(NIO1HeadStage.scala:340)
  at org.http4s.blaze.pipeline.HeadStage.closePipeline(Stages.scala:341)
  at org.http4s.blaze.pipeline.HeadStage.closePipeline$(Stages.scala:330)
  at org.http4s.blaze.channel.ChannelHead.closePipeline(ChannelHead.scala:25)
  at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:97)
  at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:90)
  at org.http4s.blazecore.IdleTimeoutStage.closePipeline(IdleTimeoutStage.scala:37)
  at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:97)
  at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:90)
  at org.http4s.blaze.server.Http1ServerStage.closePipeline(Http1ServerStage.scala:93)
  at org.http4s.blaze.server.Http1ServerStage.org$http4s$blaze$server$Http1ServerStage$$closeConnection(Http1ServerStage.scala:330)
  at org.http4s.blaze.server.Http1ServerStage.$anonfun$10$$anonfun$3(Http1ServerStage.scala:319)
  at org.http4s.blaze.server.Http1ServerStage.$anonfun$10$$anonfun$adapted$3(Http1ServerStage.scala:319)
  at cats.effect.IOFiber.runLoop(IOFiber.scala:262)
  at cats.effect.IOFiber.execR(IOFiber.scala:1319)
  at cats.effect.IOFiber.run(IOFiber.scala:118)
  at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:585)\n",
  "thread_name": "io-compute-1"
}
```
Switch from blaze server to ember could solve the problem.

### PR DESCRIPTION
**Pull request by tpacuszkapl**
closes #302

### CODE REVIEW

File: backend/src/main/twirl/MainZIOHttp4sScala3.scala.txt [hunk 1]
```diff
@@ -21,14 +22,19 @@ object Main extends ZIOAppDefault:
     val routes = ZHttp4sServerInterpreter().from(Endpoints.all).toRoutes
     }
 
-    val port = sys.env.get("HTTP_PORT").flatMap(_.toIntOption).getOrElse(8080)
+    val port = sys.env
+      .get("HTTP_PORT")
+      .flatMap(_.toIntOption)
+      .flatMap(Port.fromInt)
+      .getOrElse(Port.fromInt(8080).get)
```
Comment (adamw) [inline backend/src/main/twirl/MainZIOHttp4sScala3.scala.txt:29]: isn't there a `port` interpolator, so we could replace this `.get` with `port"8080"`?
